version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    depends_on:
      - db
    environment:
      DB_NAME: recipe_db
      DB_USER: recipe_user
      DB_PASSWORD: recipe_pass
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app

  frontend:
    build: ./Frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
